### ISSUE TITLE
Gridsome not building

### ISSUE THREAD

**Issue by u12206050** [u12206050/gridsome-firebase-starter#1]
Firebase is failing to build within the Nodejs enviroment.

```
Failed to render /login
Error: The XMLHttpRequest compatibility library was not found.
```

**Comment by u12206050** [comment]
Fixed!

Loading all firebase libraries including firebaseui via script tags instead of npm.

**Comment by hacknug** [comment]
@u12206050 did you look into adding that method to the global object? https://github.com/firebase/firebase-js-sdk/issues/349#issuecomment-379290690

I've been trying to find an alternative solution to yours (pulling files from the CDN) with no luck tho 🤷‍♂
