### ISSUE TITLE
Add routerGaurd to all pages except auth page?

### ISSUE THREAD

**Issue by milos5593** [u12206050/gridsome-firebase-starter#12]
Hi, 

I am having trouble wrapping my head around how to add router guard to every page except auth if a user is not logged in?

I tried adding it to main.js export function but that get's called before firebase is initialized and bound to Vue prototype.

Any help is greatly appreciated.

**Comment by u12206050** [comment]
You could look into [overriding App.vue](https://gridsome.org/docs/overriding-app/#overriding-appvue) and then in your mounted function do something like:
```
this.$router.beforeEach((to, from, next) => {
  if (!isAuthenticated) next('/login')
  // if the user is not authenticated, `next` is called twice
  next()
})
```

Untested but something in that line should work, else you could also add a `watch` in the `App.vue` on `$route` and check the path if it is auth then allow, else allow only if logged in.
