### ISSUE TITLE
Index.vue - user and documents not needed in data()

### ISSUE THREAD

**Issue by typerory** [u12206050/gridsome-firebase-starter#3]
I see that you have user and documents as computed properties and you are grabbing the data from the store. Since that is the case, you should not have them under `data()`

**Comment by u12206050** [comment]
In which file is this?
fyi: I havn't worked much on this for a while, have a lot of other projects at hand, let me know if you feel like contributing.

**Comment by typerory** [comment]
This would be right in the Index.vue (home) file. 

Yes, I would love to contribute. I've been working with Vue and Firebase/Firestore for the past two years. I am just learning Gridsome. I think I would need access to the firebase credentials so all of the data loads properly. typerory@gmail.com
