### ISSUE TITLE
Error when running Gridsome Develop

### ISSUE THREAD

**Issue by BetaPundit** [u12206050/gridsome-firebase-starter#8]
While running **gridsome develop**, I am getting this error:

Error: gridsome.config.js: Cannot find module './firebase-adminsdk-credentials.json' (24:22)
```
  22 |       use: 'gridsome-source-firestore',
  23 |       options: {
> 24 |         credentials: require('./firebase-adminsdk-credentials.json'),
     |                      ^
  25 |         debug: true,
  26 |         collections: [
  27 |           {
```

Would appreciate if someone can look into this.

**Comment by u12206050** [comment]
You need to add that file with that name. You can download the credentials
file from Firebase.

**Comment by u12206050** [comment]
Assuming this is fixed.
